version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: transperfumes_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: transperfumes
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  tomcat:
    build: .
    container_name: transperfumes_web
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  mysql_data:
